- id: vacuum
  name: vacuum
  description: OpenAPI linter and quality checker (native install)
  language: golang
  entry: vacuum lint
  args: [--details]
  types: [text]
  files: (^|/)(openapi|swagger)\.(json|ya?ml)$
